language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
install:
  - "pip install django==$DJANGO_VERSION --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors importlib; fi"
script:
  - "nosetests tests"
  - "flake8 --config .flake8 django_settings tests"
